export const services = [
    {
        id: 0,
        name: ["Search engine", "optimitation"],
        arrow: "../src/assets/arrowBlack.svg",
        serviceImg: "../src/assets/servicesImg/service2.png",
        bgTitle: 'green',
        bgColor: 'softgray',
        textColor: 'black',
    },
    {
        id: 1,
        name: ["Pay-per-click", "advertising"],
        arrow: "../src/assets/arrowBlack.svg",
        serviceImg: "../src/assets/servicesImg/service4.png",
        bgTitle: 'softgray',
        bgColor: 'green',
        textColor: 'black',
    },
    {
        id: 2,
        name: ["Social Media", "Marketing"],
        arrow: "../src/assets/arrowWhite.svg",
        serviceImg: "../src/assets/servicesImg/service1.png",
        bgTitle: 'softgray',
        bgColor: 'black',
        textColor: 'softgray',
    },
    {
        id: 3,
        name: ['Email','Marketing'],
        arrow: "../src/assets/arrowBlack.svg",
        serviceImg: "../src/assets/servicesImg/service5.png",
        bgTitle: 'green',
        bgColor: 'softgray',
        textColor: 'black',
    },
    {
        id: 4,
        name: ['Content','Creation'],
        arrow: "../src/assets/arrowBlack.svg",
        serviceImg: "../src/assets/servicesImg/service3.png",
        bgTitle: 'softgray',
        bgColor: 'green',
        textColor: 'black',

    },
    {
        id: 5,
        name: ['Analytics and','Tracking'],
        arrow: "../src/assets/arrowWhite.svg",
        serviceImg: "../src/assets/servicesImg/service6.png",
        bgTitle: 'green',
        bgColor: 'black',
        textColor: 'softgray',
    },
];
